# Generated by Django 3.2.9 on 2021-11-19 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=20, verbose_name='权限名')),
                ('type', models.CharField(choices=[('menu', '菜单'), ('interface', '接口')], default='interface', max_length=10, verbose_name='权限类型')),
                ('code', models.CharField(max_length=30, verbose_name='权限标识')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.permission', verbose_name='父功能')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'tb_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=20, verbose_name='角色名')),
                ('description', models.CharField(max_length=50, verbose_name='角色描述')),
                ('permissions', models.ManyToManyField(blank=True, to='authentication.Permission', verbose_name='功能权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('account_number', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('roles', models.ManyToManyField(blank=True, to='authentication.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
                'db_table': 'tb_account',
                'ordering': ['id'],
            },
        ),
    ]
