# Generated by Django 3.2.9 on 2021-11-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='authentication.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.permission', verbose_name='父功能'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='authentication.Permission', verbose_name='功能权限'),
        ),
    ]
