# Generated by Django 3.2.9 on 2021-12-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extract_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
