# Generated by Django 3.2.9 on 2021-12-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20211216_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='batch_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='config_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dataset',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='eval_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gpu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='train_rate',
            field=models.FloatField(null=True),
        ),
    ]
