# Generated by Django 3.2.9 on 2021-12-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20211220_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gpu',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='saved_model',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='train',
            field=models.BooleanField(null=True),
        ),
    ]
