# Generated by Django 3.2.9 on 2021-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20211220_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='learning_rate',
            field=models.FloatField(null=True),
        ),
    ]
