# Generated by Django 3.2.9 on 2021-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_task_learning_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dataset',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=30),
        ),
    ]
